Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      KeyName: ''
      Tags:
        - Key: Name
          Value: SampleEC2Instance
